config/routes.rb
Rails.application.routes.draw do
  
  root to: 'landing#index'

  resources :products do
    resources :reviews
  end

  post '/products' => 'products#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: :true 
  validates :cost, presence: :true
  validates :country_of_origin, presence: :true
  
  before_save(:titleize_product)

  def self.usa
    where(country_of_origin: "USA")
  end

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}

  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(10)
  )}

  private
    def titleize_product
      if self.country_of_origin.titleize == "Usa"
        self.country_of_origin = self.country_of_origin.upcase
      else
        self.name = self.name.titleize
        self.country_of_origin = self.country_of_origin.titleize
      end
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, presence: :true 
  validates :content_body, presence: :true
  validates :content_body, length: { in: 50..250 }
  validates :rating, presence: :true
  validates_inclusion_of :rating, in: 1..5 

  before_save(:titleize_review)

  private
    def titleize_review
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin
    if !(current_user && current_user["admin"])
      flash[:alert] = "You aren't authorized to visit this page."
      redirect_to '/'
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/just_another_controller.rb
class JustAnotherController < ApplicationController
  before_action :authorize, only: [:secret]

  def secret
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @products = Product.all
    @reviews = Review.all
    render :index
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :current_admin, only: [:new, :create, :edit, :update, :destroy] 

  def index
    @products = Product.all
    @reviews = Review.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product Added"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product Updated"
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :require_login
    before_action :current_admin, only: [:edit, :update, :destroy]

    def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      
      redirect_to product_path(@product)
      flash[:notice] = "Review Added"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end
  
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end

    def require_login
      unless logged_in?
        flash[:alert] = "You must be logged in to access this page"
        redirect_to '/signin'
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="jumbotron">
  <h1>Mario's Foods</h1>
  <h2>World class, specialty foods directly to your door!</h2>
  <%= link_to "Enter Site", '/products' %>
</div>
<div class="row">
  <% if @products.any? %>
    <div class="col-md-6">
      <p>Recently Added:<p>
      <ul>
        <% Product.three_most_recent.each do |most_recent| %>
          <li><%= link_to most_recent.name, product_path(most_recent) %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <p>There are no products yet.</p>
  <% end %>

  <% if @reviews.any? %>
    <div class="col-md-6">
      <p>Products with most reviews:</p>
        <% Product.most_reviews.each do |most_reviews| %>
          <li><%= link_to most_reviews.name, product_path(most_reviews) %></li>
        <% end %>
    </div>
  <% else %>
    <p>There are no reviews for any products</p>
  <% end %>
</div>

  

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit %>
 
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario's Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <div class="header">
      <% if current_user %>
            <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
          <% else %>
            <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
          <% end %>

      <%= flash[:alert] %>
      <%= flash[:notice] %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/products/index.html.erb
<h1>Mario's Foods</h1>

<% if current_user && current_user["admin"] %>
  <p><%= link_to "Add new product", new_product_path %></p>
<% else %>
  <h3>Check out these great products!</h3>
<% end %>

<div class="row">
  <% if @products.any? %>
    <div class="col-md-3">
      <p>All Products:</p>
      <ul>
        <% @products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-3">
      <p>Recently Added:<p>
      <ul>
        <% Product.three_most_recent.each do |most_recent| %>
          <li><%= link_to most_recent.name, product_path(most_recent) %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <p>There are no products yet.</p>
  <% end %>

  <% if @reviews.any? %>
    <div class="col-md-3">
      <p>Products with most reviews:</p>
        <% Product.most_reviews.each do |most_reviews| %>
          <li><%= link_to most_reviews.name, product_path(most_reviews) %></li>
        <% end %>
    </div>
  <% else %>
    <p>There are no reviews for any products</p>
  <% end %>

  <div class="col-md-3">
    <% if Product.usa.any? %>
      <p>Buy Local:</p>
      <ul>
        <% Product.usa.each do |usa| %>
          <li><%= link_to usa.name, product_path(usa) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no foods produced in the USA.</p>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<h4>Cost: $<%= @product.cost%></h4>
<h4>Country: <%= @product.country_of_origin%></h4>

<% if @product.reviews.any? %>
  <h4><u>Product Reviews</u></h4>
    <% @product.reviews.each do |review| %>
      <ul>
        <li>
          <%= link_to review.author, product_review_path(@product, review) %>
          <p>Rating: <%= review.rating%></p>
          <p>Review: <%= review.content_body %></p>
        </li>
      </ul>
    <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

 <% if current_user && current_user["admin"] %>

<p><%= link_to "Edit Product", edit_product_path(@product) %></p>
<p><%= link_to "Delete Product", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
 <% end %>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "layouts/review_form" %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "layouts/review_form" %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/reviews/show.html.erb
<h1>Reviewer: <%= @review.author %></h1>
<h3>Product: <%= @product.name %></h3>
<h3>Rating: <%= @review.rating %></h3>

<p><%= @review.content_body %></p>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>